### ISSUE TITLE
Changing the webadmin password does not work

### ISSUE THREAD

**Issue by jinxmcg** [litespeedtech/ols-docker-env#11]
Hi,

Using does not change the password

```
./bin/webadmin.sh newpassword

cat /usr/local/lsws/admin/conf/htpasswd
admin:
Parse error: syntax error, unexpected '{' in /usr/local/lsws/admin/fcgi-bin/admin_php.bak on line 2030
```

The fix is to remove the * from the line 64 in webadmin.sh as it picksup a bak file
```php
'echo "admin:$(/usr/local/lsws/admin/fcgi-bin/admin_php* -q /usr/local/lsws/admin/misc/htpasswd.php '${1}')" > /usr/local/lsws/admin/conf/htpasswd';
```

**Comment by Code-Egg** [comment]
Hi,
Thanks for the report. Although I'm not sure why there has a bak file there, still push a fix for it. https://github.com/litespeedtech/ols-docker-env/commit/412e1e97e08ce222f260dba8d027a4eb20becaaa

**Comment by jinxmcg** [comment]
I think I did issue an update before trying to change password
```bash 
bin/webadmin.sh [-U, --upgrade]
```

**Comment by Code-Egg** [comment]
ok, just tested and it works, will close it.
