### ISSUE TITLE
Virtual Hosts not created on OpenLiteSpeed

### ISSUE THREAD

**Issue by leandrofreires** [litespeedtech/ols-docker-env#14]
following the tutorial, when I create a domain described as in [tutorial](https://github.com/litespeedtech/ols-docker-env#creating-a-domain-and-virtual-host)
does not appear on the panel in Virtual Host List, is this behavior normal? should I add manually?

**Comment by Code-Egg** [comment]
Hi,

It created base on the template.  So you might want to take a look VHost Templates > Docker template, and the new created virtual host should be there.

**Comment by leandrofreires** [comment]
@Code-Egg  thanks, i'll be done, any doubt i'll ask on the slack now that i got in, i'll see if i make a pull request to fix the broken links
