### ISSUE TITLE
docker-compose up 

### ISSUE THREAD

**Issue by rahulkathet** [litespeedtech/ols-docker-env#15]
Pulling mysql (mariadb:10.3.17)...
10.3.17: Pulling from library/mariadb
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries

**Comment by Code-Egg** [comment]
Hi,
No idea yet, maybe need more information. I just did a fresh setup, no such issue. Is it a fresh installation, or did you change anything?  Can you share the whole output with the command `docker-compose up`?
