### ISSUE TITLE
Complex password for mysql

### ISSUE THREAD

**Issue by Gershon-A** [litespeedtech/ols-docker-env#16]
Hello,
seems a complex password with special characters for mysql trow error.
my .env line 5 has:
`MYSQL_ROOT_PASSWORD=g3qqET9&BZZoJdP4t3Wq`
```
bash bin/database.sh -D domain.io
.env: line 5: BZZoJdP4t3Wq: command not found
```
I changed the password to 
`MYSQL_ROOT_PASSWORD=g3qqET9`
All work as expected.

**Comment by Code-Egg** [comment]
Hi,

Failed to run with command `docker run --name mariadb-test -e MYSQL_ROOT_PASSWORD=password&123 -d mariadb:10.3.17`
But it works when password with some other w/o special characters, e.g. `-`, `=` instead of `&`. 

Best,
Eric

**Comment by Gershon-A** [comment]
Yes. Without special characters all works.
This is a good idea to add support for complex passwords.
Thank You!

**Comment by Code-Egg** [comment]
No problem, since we include it from the official MariaDB image, better raise the issue with them https://github.com/docker-library/mariadb/issues

issue close
