### ISSUE TITLE
404 Not Found nginx

### ISSUE THREAD

**Issue by simplenotezy** [litespeedtech/ols-docker-env#18]
I ran the `demosite.sh` as per https://www.youtube.com/watch?v=S16spQxajas&feature=youtu.be, but once created, and I visit "localhost" I get a 404:

https://localhost/
![image](https://user-images.githubusercontent.com/3786627/100008763-26a82a00-2dce-11eb-9eee-a0bdb3e1258b.png)

I can access LiteSpeed WebAdmin at https://localhost:7080/ though.

```
CONTAINER ID        IMAGE                                        COMMAND                  CREATED             STATUS              PORTS                                                                                    NAMES
bd81448c764d        litespeedtech/openlitespeed:1.6.15-lsphp74   "/entrypoint.sh"         19 minutes ago      Up 10 minutes       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:7080->7080/tcp, 0.0.0.0:443->443/udp   litespeed-docker_litespeed_1
232dfe161ae6        mariadb:10.3.17                              "docker-entrypoint.s…"   19 minutes ago      Up 10 minutes       0.0.0.0:3306->3306/tcp                                                                   litespeed-docker_mysql_1
02f4189df59e        bitnami/phpmyadmin:5.0.2-debian-10-r72       "/app-entrypoint.sh …"   19 minutes ago      Up 10 minutes       0.0.0.0:8080->80/tcp, 0.0.0.0:8443->443/tcp                                              litespeed-docker_phpmyadmin_1
```

**Comment by simplenotezy** [comment]
After restarting docker-compose, I can't access LiteSpeed webadmin anymore either: https://localhost:7080/ (getting REFUSED TO CONNECT).

![image](https://user-images.githubusercontent.com/3786627/100009261-ebf2c180-2dce-11eb-830d-97caf3fbf4ea.png)

**Comment by Code-Egg** [comment]
> I ran the `demosite.sh` as per https://www.youtube.com/watch?v=S16spQxajas&feature=youtu.be, but once created, and I visit "localhost" I get a 404:
> 
> https://localhost/
> ![image](https://user-images.githubusercontent.com/3786627/100008763-26a82a00-2dce-11eb-9eee-a0bdb3e1258b.png)
> 
> I can access LiteSpeed WebAdmin at https://localhost:7080/ though.
> 
> ```
> CONTAINER ID        IMAGE                                        COMMAND                  CREATED             STATUS              PORTS                                                                                    NAMES
> bd81448c764d        litespeedtech/openlitespeed:1.6.15-lsphp74   "/entrypoint.sh"         19 minutes ago      Up 10 minutes       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:7080->7080/tcp, 0.0.0.0:443->443/udp   litespeed-docker_litespeed_1
> 232dfe161ae6        mariadb:10.3.17                              "docker-entrypoint.s…"   19 minutes ago      Up 10 minutes       0.0.0.0:3306->3306/tcp                                                                   litespeed-docker_mysql_1
> 02f4189df59e        bitnami/phpmyadmin:5.0.2-debian-10-r72       "/app-entrypoint.sh …"   19 minutes ago      Up 10 minutes       0.0.0.0:8080->80/tcp, 0.0.0.0:8443->443/tcp                                              litespeed-docker_phpmyadmin_1
> ```

Did you run the setup on your local computer/server? It shows Nginx, something not right, you might have some other services running on port 80.

**Comment by simplenotezy** [comment]
@Code-Egg You're right. I also check this yesterday, but it only appears to be docker that listens on port 80:

    com.docke 24857   mf   72u  IPv6 0xa3b81cbe60b1dd49      0t0  TCP *:80 (LISTEN)

If I run `docker ps` I see no containers running at all, however, when I run `docker-compose up` and then run `docker ps` I get:

```
CONTAINER ID        IMAGE                                        COMMAND                  CREATED              STATUS              PORTS                                                                                    NAMES
cb536bfd3afb        81d7cdfa4169                                 "/usr/bin/dumb-init …"   About a minute ago   Up About a minute                                                                                            k8s_controller_ingress-nginx-controller-c4f944d4d-jkztf_ingress-nginx_af3c7733-aa56-4019-9b8c-b5fb06fe923b_10
bd81448c764d        litespeedtech/openlitespeed:1.6.15-lsphp74   "/entrypoint.sh"         13 hours ago         Up 48 seconds       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:7080->7080/tcp, 0.0.0.0:443->443/udp   litespeed-docker_litespeed_1
232dfe161ae6        mariadb:10.3.17                              "docker-entrypoint.s…"   13 hours ago         Up 48 seconds       0.0.0.0:3306->3306/tcp                                                                   litespeed-docker_mysql_1
02f4189df59e        bitnami/phpmyadmin:5.0.2-debian-10-r72       "/app-entrypoint.sh …"   13 hours ago         Up 48 seconds       0.0.0.0:8080->80/tcp, 0.0.0.0:8443->443/tcp                                              litespeed-docker_phpmyadmin_1
```

Perhaps it's the k8s ingress controller? It's weird because I appeared after running `docker-compose up`.

**Comment by simplenotezy** [comment]
OK, I solved the issue. It appeared that kubernetes was running (via Docker Desktop), even though I manually killed all pods. I had to go to Preferences -> Reset Kubernetes Cluster, to get it working.

Thanks for your insight @Code-Egg !

**Comment by Code-Egg** [comment]
Great, good to know that you fixed it.
