### ISSUE TITLE
data/db in gitignore

### ISSUE THREAD

**Issue by simplenotezy** [litespeedtech/ols-docker-env#19]
Currently playing a bit around with ols. I guess I need to add `data/db` to `.gitignore` file, since it's being added in my git repo currently, but I was wondering why this haven't been added to the already present gitignore files. Am I missing something specific to OLS?

**Comment by Code-Egg** [comment]
Hi,
Sure, if you don't mind, please send a PR. Thanks.
Either add a `data/db` to .gitignore or update `data` to `data/` should works. 
https://github.com/litespeedtech/ols-docker-env/blob/master/.gitignore#L1

**Comment by simplenotezy** [comment]
Awesome @Code-Egg - Will work on a PR
