### ISSUE TITLE
Setting up a OLS site in Dockerfile

### ISSUE THREAD

**Issue by simplenotezy** [litespeedtech/ols-docker-env#20]
When setting up OLS site through docker/compose, am I required to add any configuration/run any specific OLS commands, apart from copying my site into `sites/name/html/`?

**Comment by Code-Egg** [comment]
Hi,

To migrate a site, we might want to create a virtual host on the webserver. 
https://docs.litespeedtech.com/cloud/docker/ols+wordpress/#creating-a-domain-and-virtual-host
```
bash bin/domain.sh [-A, --add] example.com
```
Then move your site to the sites/example.com/html/ and migrate the DB. 

Pointing the domain and apply LE if you want
https://docs.litespeedtech.com/cloud/docker/ols+wordpress/#install-acme

Let us know if it works.

**Comment by simplenotezy** [comment]
Thanks for prompt reply 😊

So just to verify I understand it correctly:

I can have the directory in `/sites/mysite.com/html` and then run `bin/domain.sh --add mysite.com` afterwards in my `Dockerfile` -- assuming that `domain.sh` won't recreate the mysite.com/html folder.

Is that correctly understood?

**Comment by Code-Egg** [comment]
No problem. 
We run the `bin/domain.sh --add mysite.com` first so it will add the domain to Listener and auto create a new virtual host."
Yes, it will be skipped if the folder already exists. In this case, you will need to manually add the domain to the listener.

**Comment by simplenotezy** [comment]
@Code-Egg How can I manually add the domain to the listener? I am writing a Dockerfile  from a folder, where my main site's content is already in the folder `/sites/mysite.com/html` when setting up Docker. 

Should I simply call: `bin/domain.sh --add mysite.com` in my `Dockerfile`? Or should I run some different command when, in my case, the content folder is stored in github and thus is included with the Dockerfile.

**Comment by Code-Egg** [comment]
Hi, 
Yes, the domain add command should works even the folder exists. 
```
bin/domain.sh --add mysite.com
```

**Comment by simplenotezy** [comment]
Thanks for such prompt answers, @Code-Egg. I have tried that, but getting error: `bash: bin/domain.sh: No such file or directory`

```
Building litespeed
Step 1/4 : FROM litespeedtech/openlitespeed:1.6.15-lsphp74
 ---> 45db35fd0e80
Step 2/4 : COPY ./lsws/php/. /usr/local/lsws/lsphp74/etc/php/7.4/mods-available/
 ---> Using cache
 ---> 263bd87e8661
Step 3/4 : RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar &&     php wp-cli.phar --info &&      chmod +x wp-cli.phar &&      mv wp-cli.phar /usr/local/bin/wp
 ---> Using cache
 ---> 3ac7a50870f8
Step 4/4 : RUN bash bin/domain.sh --add mydomain.test
 ---> Running in db3a5f73bf31
bash: bin/domain.sh: No such file or directory
```

**Comment by Code-Egg** [comment]
No problem, @simplenotezy 

Did you add `bash bin/domain.sh --add mydomain.test` from your custom dockerfile? The command is designed to run it in the local server manually instead of the dockerfile. It should have no such docker-compose command not found issue if you run the command manually.  

Best

**Comment by simplenotezy** [comment]
Ah I see @Code-Egg. How may I add the domain manually in a Dockerfile?

**Comment by simplenotezy** [comment]
This seemed to do the trick:


```
# Copy over sites
COPY ./lsws/conf /usr/local/lsws/conf
COPY ./lsws/admin-conf /usr/local/lsws/admin/conf
COPY ./bin/container /usr/local/bin
COPY ./sites /var/www/vhosts
COPY ./acme /root/.acme.sh/
COPY ./logs /usr/local/lsws/logs 

# Add domain
RUN su -s /bin/bash lsadm -c "cd /usr/local/lsws/conf && domainctl.sh --add mydomain.com"
```
