### ISSUE TITLE
Error when run -mod-secure enable

### ISSUE THREAD

**Issue by IRediTOTO** [litespeedtech/ols-docker-env#23]
Hi I got this error. is it normal or an error? 
```
bash bin/webadmin.sh --mod-secure enable
Install git
Download OWASP rules
Config OWASP rules.
/usr/local/bin/owaspctl.sh: line 192: cd: /usr/local/lsws/conf/owasp/owasp-modsecurity-crs: No such file or directory        
/usr/local/bin/owaspctl.sh: line 196: cd: /usr/local/lsws/conf/owasp/owasp-modsecurity-crs/rules: No such file or directory  
Enable modsecurity
```
When I run inside litespeed container I just see those files
```
root@a27250847e47:/usr/local/lsws/conf/owasp# ls
modsec_includes.conf  modsecurity.conf
```

**Comment by Code-Egg** [comment]
Hi,

If successful, you should see "modsec_includes.conf", "modsecurity.conf" and "owasp-modsecurity-crs" folder. 
I just tried and no such issue, could you try it again, maybe the rule folder was not able to download at that moment.
