### ISSUE TITLE
Change max_upload_filesize PHP not work

### ISSUE THREAD

**Issue by IRediTOTO** [litespeedtech/ols-docker-env#24]
hi, I go to file php.ini in folder `lsws/admin-conf/` on host machine which is volume of ols
I changed it and edit it, then I tried to run 
`docker-compose exec litespeed su -c '/usr/local/lsws/bin/lswsctrl restart >/dev/null'`
to restart ols
Finanlly I still can't upload file more than too 2MB to wp.

Where can I edit php.ini? How can restart the php?
I tried to kill lsphp in container litespeed but command not work....
```
killall -9 lsphp
lsphp: no process found
```

Hope you can help me find this out.

**Comment by Code-Egg** [comment]
Try 
```
docker-compose exec litespeed su -c 'pkill lsphp'
```
