### ISSUE TITLE
Add auto-install missing packages to phpbuild

### ISSUE THREAD

**Issue by websharik** [litespeedtech/ols-docker-env#25]
I have 6 missing packages and 50%+ required some caption changes as *-dev or full another caption (google help me to search required captions, but i lost time while do it).

*Total:*
```
apt install gcc libxml2-dev build-essential libexpat1-dev libgeoip-dev libpng-dev libpcre3-dev libssl-dev libxml2-dev rcs zlib1g-dev libmcrypt-dev libcurl4-openssl-dev libjpeg-dev libpng-dev libwebp-dev pkg-config libsqlite3-dev libonig-dev libzip-dev -y
```

**gcc**
```
checking for pkg-config... no
checking for cc... no
checking for gcc... no
```
```
apt install gcc -y
```

**libxml**
```
checking for libxml-2.0 >= 2.9.0... no
```
```
apt install libxml2-dev -y
```

**openssl**
```
checking for openssl >= 1.0.1... no
No package 'openssl' found
```
```
apt install build-essential libexpat1-dev libgeoip-dev libpng-dev libpcre3-dev libssl-dev libxml2-dev rcs zlib1g-dev libmcrypt-dev libcurl4-openssl-dev libjpeg-dev libpng-dev libwebp-dev pkg-config
```

**sqlite3**
```
checking for sqlite3 > 3.7.4... no
configure: error: Package requirements (sqlite3 > 3.7.4) were not met:
No package 'sqlite3' found
```
```
apt install libsqlite3-dev
```

**oniguruma**
```
checking for oniguruma... no
configure: error: Package requirements (oniguruma) were not met:
No package 'oniguruma' found
```
```
apt install libonig-dev
```

**libzip**
```
checking for libzip >= 0.11 libzip != 1.3.1 libzip != 1.7.0... no
configure: error: Package requirements (libzip >= 0.11 libzip != 1.3.1 libzip != 1.7.0) were not met:
No package 'libzip' found
```
```
apt install libzip-dev
```

**Comment by Code-Egg** [comment]
Hi, 

Thanks for the report. To keep it lightweight, we try not to install any extra package as possible, e.g. vim, libzip, openssl and object cache services. But it should be easy for you to build a new one with those packages included, see https://docs.litespeedtech.com/cloud/docker/ols+wordpress/#customization

**Comment by websharik** [comment]
@Code-Egg, Lightweight is good and it will stay same. I mean about only phpbuild script, on checking extra packages script call user to install not found package, but auto install not found package will be more convenient.

**Comment by Code-Egg** [comment]
HIHI, 
Although we plan not to add this to the PHP build, user can found it from our doc, 
https://docs.litespeedtech.com/extapp/php/getting_started/#source-prereqs 
So close the issue.
