### ISSUE TITLE
prestashop deployment 

### ISSUE THREAD

**Issue by lucmichalski** [litespeedtech/ols-docker-env#28]
Hi guys,

Hope you are all well !

I was wondering if it would be possible to have a docker-compose with ols+prestashop configured because I would like to test your Prestashop module and get a preview of the performances provided by ols.

Do you have any comparison/benchmarks of ols vs varnish or redis cache ?

Thanks for any insights or inputs on these questions. 

Cheers,
Luc Michalski

**Comment by Code-Egg** [comment]
If you want to use the LiteSpeed cache plugin for PrestaShop, you will need LiteSpeed Enterprise.

**Comment by lucmichalski** [comment]
Ok, we will subscribe but we want a turnkey deployment to save time.

**Comment by Code-Egg** [comment]
Currently, there's no existing LiteSpeed + PrestaShop docker solution. You might want to create a new one. If docker is not a must, maybe deploy PrestaShop via the control panel, e.g. cPanel, CyberPanel is an option for you?

**Comment by lucmichalski** [comment]
I prefer to use docker, I do not have cpanel or cyberpanel.

Is there a way to create a repo and draft a prestashop bundle ? I would be more than happy to help

**Comment by Code-Egg** [comment]
Hi @lucmichalski ,
I start the PrestaShop on this repo: https://github.com/Code-Egg/lsws-prestashop-docker-env which is based on https://github.com/litespeedtech/lsws-magento-docker-env. There's a DB connection issue need to be fixed, I will try to make it works when getting any chance

**Comment by lucmichalski** [comment]
Awesome thanks ! I ll wait for your fix before testing it ! 

Btw. I started a prestashop kubernetes heml chart. Did you create something around k8s pour litespeed ?

Ref. https://github.com/lucmichalski/prestashop-k8s

**Comment by Code-Egg** [comment]
Hi,
It should work now. 
```
git clone https://github.com/Code-Egg/lsws-prestashop-docker-env.git
```
Open a terminal, `cd` to the folder in which docker-compose.yml is saved, and run:
```
docker-compose up -d
```
Note: Edit the .env file to update the demo site domain, default MySQL user, and password.

Starting a Demo Site
```
bash bin/demosite.sh -P
```

Nope, we haven't got a chance to extend the service to k8s, but you could try Jelastic which has LiteSpeed supported and auto-scaling, they also have many extensions for users.
