### ISSUE TITLE
MariaDB keeps restarting

### ISSUE THREAD

**Issue by Dan0sz** [litespeedtech/ols-docker-env#29]
Hi guys,

I'm trying to use this image to create a local docker environment. I'm on Windows 10 with Ubuntu 20.04 running as a subsystem. I'm using the WSL 2 based engine -- if that matters.

After running `docker-compose up -d` all seems good, but MariaDB keeps restarting, making it impossible for me to do things like create a database, etc.

![afbeelding](https://user-images.githubusercontent.com/18595395/118149881-467de980-b412-11eb-9beb-6aea6f30b7fa.png)

Please let me know what you need in order to debug this issue!

**Comment by Code-Egg** [comment]
Hi,

What if you run `docker-compose up` without -d and check if there's any error shows on the MySQL section, maybe the port is occupied by other services?

**Comment by Dan0sz** [comment]
You're right, @Code-Egg. Stupid of me that I didn't think of that 😅 

Anyway, this is the output

````
mysql_1       | 2021-05-17 12:35:48+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql_1       | 2021-05-17 12:35:48+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.5.9+maria~focal started.
mysql_1       | 2021-05-17 12:35:48+00:00 [ERROR] [Entrypoint]: Database is uninitialized and password option is not specified
mysql_1       |         You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
````

My local environment doesn't use a db password, so where do I specify MYSQL_ALLOW_EMPTY_PASSWORD? I added it to .env with a value of 1 but that doesn't seem to work.

**Comment by Code-Egg** [comment]
https://github.com/litespeedtech/ols-docker-env/blob/master/docker-compose.yml
Although the MariaDB image supports the MARIADB_ALLOW_EMPTY_ROOT_PASSWORD variable, the docker-compose.yml has already designed to import those values from the .env file, so you might want to keep all default variables on .env to make it works.

**Comment by Dan0sz** [comment]
I ended up just setting a password, because neither of the mentioned variables seemed to solve anything in .env.

Anyway, thanks!
