### ISSUE TITLE
WordPress Increase File Upload Size

### ISSUE THREAD

**Issue by knkrth** [litespeedtech/ols-docker-env#32]
Hi, How to increase WordPress file upload size `The uploaded file exceeds the upload_max_filesize directive in php.ini.` I tried all three methods on https://www.wpbeginner.com/wp-tutorials/how-to-increase-the-maximum-file-upload-size-in-wordpress/ 

Added `PHP.INI ` file, Tried `.htaccess ` 

Even tried 3rd party plugin on WordPress It shows the changed size but it won't let me to upload.

![image](https://user-images.githubusercontent.com/12738581/121561233-ef316000-ca35-11eb-9ef2-5c7fce2feafa.png)

**Comment by qtwrk** [comment]
run `find /usr/local/lsws -name php.ini` to find the php.ini file for your php version , then edit that php.ini , after that , do `pkill lsphp` to restart PHP

**Comment by knkrth** [comment]
@qtwrk Tried `find /usr/local/lsws -name php.ini` & got the following results,
```
localhost/html# find /usr/local/lsws -name php.ini
/usr/local/lsws/admin/misc/php.ini
/usr/local/lsws/admin/conf/php.ini
/usr/local/lsws/admin/.conf/php.ini
/usr/local/lsws/lsphp74/etc/php/7.4/litespeed/php.ini
/usr/local/lsws/lsphp80/etc/php/8.0/litespeed/php.ini
```
First I edited php.ini on php 8.0 but still no change, Even I tried restart the server by `/usr/local/lsws/bin/lswsctrl restart` still no change. So I make changes to all php.ini files STILL no  change 😞

![image](https://user-images.githubusercontent.com/12738581/121565783-6ec12e00-ca3a-11eb-9adb-698315be54dd.png)

**Comment by qtwrk** [comment]
I asked you to restart the PHP by `pkill lsphp` , not sure why you restarted the webserver ...

run `grep "upload_max_filesize" /usr/local/lsws/lsphp80/etc/php/8.0/litespeed/php.ini` and `grep "post_max_size" /usr/local/lsws/lsphp80/etc/php/8.0/litespeed/php.ini` to confirm the new value , then run `pkill lsphp` to restart php process.

**Comment by qtwrk** [comment]
create a phpinfo page , see what is your main php.ini , then edit that one

**Comment by knkrth** [comment]
> I asked you to restart the PHP by `pkill lsphp` , not sure why you restarted the webserver ...
> 
> run `grep "upload_max_filesize" /usr/local/lsws/lsphp80/etc/php/8.0/litespeed/php.ini` and `grep "post_max_size" /usr/local/lsws/lsphp80/etc/php/8.0/litespeed/php.ini` to confirm the new value , then run `pkill lsphp` to restart php process.

Solved the issue by editing `/usr/local/lsws/lsphp80/etc/php/8.0/litespeed/php.ini` & Confirmed it by the above command. 
Thanks 🙂

**Comment by knkrth** [comment]
Providing these php values in `.env` file would be helpful.

**Comment by Code-Egg** [comment]
I will note this down as a feature request
