### ISSUE TITLE
A Quick appreciation

### ISSUE THREAD

**Issue by aaditya-cpu** [litespeedtech/ols-docker-env#36]
This is a beautiful piece of code you have written,
I just want to appreciate the simplicity. I have just started the back-end of web development.

**Comment by aaditya-cpu** [comment]
Please feel free to close it

**Comment by aaditya-cpu** [comment]
+ umm I hope this setup is viable for a multi site env. in wordpress

**Comment by Code-Egg** [comment]
Thanks. Also, multi-site should work.
