### ISSUE TITLE
Demosite script not working in a fresh install

### ISSUE THREAD

**Issue by ltroya-as** [litespeedtech/ols-docker-env#37]
Hi there,

I am trying this repo for the first time. I followed the instructions on the README.md but the `bin/demosite.sh` is not working for me. I see a  `503 Service Unavailable` after several seconds.

I see this error on the log `Aborted connection 3 to db: 'unconnected' user: 'unauthenticated' host: '172.23.0.4' (This connection closed normally without authentication)`

The steps I did was:

```
docker-compose up -d
./bin/demosite.sh
```

Output for the command:

```
[O] The root folder ./sites/localhost/ exist.
Database wordpress already exist, skip DB creation!
Storing database parameter
Install unzip package..
Install ed package..
Service finished, enjoy your accelarated LiteSpeed server!
```

I see the correct configuration on `sites/localhost/html/wp-config.php`

```php
/** The name of the database for WordPress */
define('DB_NAME', 'wordpress');

/** Database username */
define('DB_USER', 'wordpress');

/** Database password */
define('DB_PASSWORD', 'password');

/** Database hostname */
define('DB_HOST', 'mysql');
```

And I am using the default values for the `.env` file:

```
TimeZone=America/New_York
OLS_VERSION=1.7.15
PHP_VERSION=lsphp80
MYSQL_DATABASE=wordpress
MYSQL_ROOT_PASSWORD=password
MYSQL_USER=wordpress
MYSQL_PASSWORD=password
DOMAIN=localhost
```

Is there anything I am missing? 

Docker version: `Docker version 20.10.10, build b485636`
Docker compose version: `docker-compose version 1.27.4, build 40524192`

Kind regards

**Comment by Code-Egg** [comment]
I launched a new one no such issue. May I know if mariadb container is up and running? and are you able to visit it with port 8080/8443 and login with the given password?

**Comment by ltroya-as** [comment]
@Code-Egg 

Oh, I turned off my computer to respond to you and I can access it. Maybe it is necessary to restart the `litespeed` container after running the `demosite.sh` or `appinstall.sh` script?

**Comment by Code-Egg** [comment]
Container restart is not needed in general, maybe there's something wrong with the first-time installation. Thats normal, please visit 8080 with http, and 8443 with https.

**Comment by ltroya-as** [comment]
@Code-Egg Understood. Thank you so much for the help!
