### ISSUE TITLE
Multi tenant VPS

### ISSUE THREAD

**Issue by isvaljek** [litespeedtech/ols-docker-env#40]
Hi, what would be the recommended route to setup a multi tenant VPS, with process separation at user level?
I would also need it reverse proxy an Elastic Search and a Node.js instance on the same server.
Is it possible with this repo?

**Comment by Code-Egg** [comment]
This setup is mainly for WordPress, so you will need to manually set up other containers for ELS and NodeJS as well as to config the OLS as a reverse proxy.

**Comment by isvaljek** [comment]
Thank you, what about user separation? Is it possible to run OLS as non-root?

**Comment by Code-Egg** [comment]
Only the main openlitespeed process runs as the root user, the sub-process and PHP will run as non-root

**Comment by isvaljek** [comment]
So, there non-root Docker movement, it's not applicable here?
