### ISSUE TITLE
How to connect to an External Database

### ISSUE THREAD

**Issue by xeontcs** [litespeedtech/ols-docker-env#45]
Hi,

Is it possible to connect to an External Database?

I'd like to use External Database for Wordpress but keep failing. "Error establishing a database connection"

in the wp-config.php, I tried 127.0.0.1:3307 (Yes, the Port is 3307)

Thank you.

**Comment by Code-Egg** [comment]
127.0.0.1 means localhost, so the external database here you mean a database container and lsws container are in the same host server? By default, there's a MariaDB container setup already, check https://github.com/litespeedtech/ols-docker-env/blob/master/docker-compose.yml#L3-L17, and you can connect with "mysql". If you want to connect with 127.0.0.1, you might want to Edit docker-compose.yml and add `network_mode: "host"` under the litespeed service.

**Comment by xeontcs** [comment]
@Code-Egg 

Thank you!!
Yes, Both containers are on the same host.
I ended with "docker run -d --name openlitespeed --link mysql8...."
I will try your solution.
Thanks again.
