### ISSUE TITLE
Scripts fail due to breaking docker compose change

### ISSUE THREAD

**Issue by Darkknight33** [litespeedtech/ols-docker-env#48]
Docker-Compose has moved to a plugin, which is called via 'docker compose' and will no longer recognize 'docker-compose', so most of your scripts fail.

Edit: Previously suggested solution doesn't work. Doesn't matter as I can't seem to get a functional site regardless using the provided scripts. Even when replacing the docker-compose commands in the scripts, it still fails with this in the logs:

"2022-10-25 13:53:43 3 [Warning] Aborted connection 3 to db: 'unconnected' user: 'unauthenticated' host: '172.22.0.3' (This connection closed normally without authentication)"

It never actually connects to the DB.

**Comment by Code-Egg** [comment]
Thanks for the report, I will help to renew it. 
A workaround method is creating a file **/bin/docker-compose** with the following content,
```
docker compose "$@"
```
Give it exec permission, and it will start working. 
```
sudo chmod +x /bin/docker-compose
```

**Comment by Code-Egg** [comment]
@Darkknight33 
docker compose implemented in the latest commit, feel free to try it.

**Comment by Darkknight33** [comment]
Thank you for the update. I had already performed a find and replace in the scripts. The other problem I was having was related to using an incorrect quote character in my traefik config.  

Regardless, thanks for the quick update.

**Comment by Code-Egg** [comment]
No problem, thanks for the report. Will close the issue
