### ISSUE TITLE
mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known

### ISSUE THREAD

**Issue by mojtabaghaseemi** [litespeedtech/ols-docker-env#49]
hi 

your package has a bug
In the first installation, the server works well, but when the server is restarted

It is no longer possible to access the database

And the following error is received:
**mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known**

**Comment by Code-Egg** [comment]
Hi,

I tried to restart the server, and also `docker compose restart`, but no such issue. Could you check if the DB container is running? 
What if you run `docker compose exec -T mysql su -c "mysql -uroot -p${MYSQL_ROOT_PASSWORD} -e 'status'"` from the host server? Any output? (please replace the MYSQL_ROOT_PASSWORD with your real password)
