### ISSUE TITLE
Official Image on dockerhub

### ISSUE THREAD

**Issue by publicarray** [litespeedtech/ols-docker-env#5]
Is there a plan to add an official image to docker hub? Both the OpenSource and Commercial images?

https://hub.docker.com/u/litespeedtech https://hub.docker.com/search?q=litespeed&type=image https://hub.docker.com/search?q=openlitespeed&type=image

**Comment by Code-Egg** [comment]
It is the plan, but it (https://github.com/docker-library/official-image ) seems many rules need to satisfy, so no ETA. If you don't mind, both beta versions are on the dockerhub https://hub.docker.com/u/litespeedtech. Feel free to raise any issue you found.

**Comment by publicarray** [comment]
@Code-Egg No problems so far :)
I just wanted to inform you that the latest version is V1.6.10 https://openlitespeed.org/release-log/version-1-6-x/

Something I noticed regarding Http3 support:
At the moment the latest http3 draft supported on openlitespeed is h3-25. However Firefox appears to only negotiate with h3-27. When is h3-27 making it's way to openlitespeed?


OpenLiteSpeed (h3-25): ![OpenLiteSpeed](https://user-images.githubusercontent.com/5497998/77732141-5abd2680-7058-11ea-918b-f57ba8ba55e1.png)

h3-27 server: ![Http3 server](https://user-images.githubusercontent.com/5497998/77732153-5f81da80-7058-11ea-83bf-bddf12422f8e.png)

**Comment by Code-Egg** [comment]
Hi @publicarray ,

Thanks, just built latest version. 

Enterprise version is supported, so OpenLiteSpeed will support soon, if not on 1.6.10, then should be on the next version. Have you tried 1.6.10 and only shows h3-25 draft? 

Not sure about the last question "-" when it is not means.  More information may help.

**Comment by publicarray** [comment]
Thanks heaps, yes 1.6.10 [has it](https://http3check.net/?host=https%3A%2F%2Fdns.seby.io%2F)! 🎉  Unfortunately Firefox Nightly crashes quite reliably with http/3 turned on... I guess I'll have to wait a bit longer or switch to a chromium browser..

Hm I assumed for `vary` header to work properly the header has to be the same for all requests, compressed or not but this appears to be beyond by pay-grade:

```sh
# openlitespeed
$ curl -s -I -H 'accept-encoding: gzip, deflate' https://dns.seby.io/ | grep vary
vary: Accept-Encoding

$ curl -s -I  https://dns.seby.io/ | grep vary

# google
$ curl -s -I -H 'accept-encoding: gzip, deflate' https://www.google.com/ | grep vary

$ curl -s -I  https://www.google.com/ | grep vary
vary: Accept-Encoding
 
# facebook
$ curl -s -I -H 'accept-encoding: gzip, deflate' https://www.facebook.com | grep vary
vary: Accept-Encoding

$ curl -s -I https://www.facebook.com | grep vary
vary: Accept-Encoding

# youtube
$ curl -s -I -H 'accept-encoding: gzip, deflate' https://www.youtube.com | grep vary

$ curl -s -I https://www.youtube.com | grep vary
vary: Accept-Encoding

# cloudflare
$curl -s -I -H 'accept-encoding: gzip, deflate' https://www.cloudflare.com | grep vary
vary: Accept-Encoding

$curl -s -I https://www.cloudflare.com | grep vary
vary: Accept-Encoding
```

**Comment by Code-Egg** [comment]
Client/Browser auto send the compress request(-H 'accept-encoding: gzip, deflate'), so first example explain compression works. 
`curl -s -I -H 'accept-encoding: gzip, deflate' https://dns.seby.io/ | grep vary`
```
vary: Accept-Encoding
```
So no need to worry in my opinion. 

Going to close the issue since new version built and http3 protocol support 27 draft already
Feel free to open a new issue anytime.

**Comment by publicarray** [comment]
The Vary header is for caches, so that they know to cache different version for a different `accept-encoding` header. Your right it's not really a big issue I'm just surprised that the header is missing in some cases.
