### ISSUE TITLE
Setup SSL is not working

### ISSUE THREAD

**Issue by nguyenrom** [litespeedtech/ols-docker-env#53]
I have tried with command: ./bin/acme.sh [-D, --domain] example.com to setup SSL. I have successfully set up but site is not working.

Can you see:

<img width="708" alt="CleanShot 2023-02-22 at 22 15 47@2x" src="https://user-images.githubusercontent.com/7044465/220666066-b1fd7cd3-ba40-45d4-9f60-6ba4a5ffed09.png">

<img width="739" alt="CleanShot 2023-02-22 at 22 16 20@2x" src="https://user-images.githubusercontent.com/7044465/220666210-63158a9e-7739-4257-8704-2569562eb703.png">

**Comment by Code-Egg** [comment]
Hi,

Have you removed the site? 
```
curl -I http://n-ols-24-2.tabb.website/
HTTP/1.1 404 Not Found
date: Thu, 23 Feb 2023 03:05:26 GMT
server: LiteSpeed
connection: Keep-Alive
```

**Comment by nguyenrom** [comment]
Hi @Code-Egg , 

I have inserted index.html, can you help me to check again.

Here is the step i did:
1. Deploy new VM (Ubuntu 22.04)
2. Install ols-docker-env
3. Make new site
4. Setup SSL follow tutorial

<img width="837" alt="CleanShot 2023-02-23 at 12 40 00@2x" src="https://user-images.githubusercontent.com/7044465/220829028-14eb6670-2ebb-4ad3-8e28-0f7d32d9e6ae.png">

**Comment by Code-Egg** [comment]
HI @nguyenrom
 
I found the issue, it seems acme set ecc as the default key now, so the default cert and key path do not match the applied certificate path. 

To manually fix it, please open the openlitespeed web admin > VHost Templates > SSL, and update from 
```
/root/.acme.sh/certs/$VH_NAME/$VH_NAME.key
/root/.acme.sh/certs/$VH_NAME/fullchain.cer
```
to 
```
/root/.acme.sh/certs/$VH_NAME_ecc/$VH_NAME.key
/root/.acme.sh/certs/$VH_NAME_ecc/fullchain.cer
```
And it should start working. 

Or you can remove the image and start over again, I have the new image with the config updated and pushed. 
See https://github.com/litespeedtech/ols-dockerfiles/commit/2cae3359985e9f8da85209426ad235024cae779e

**Comment by nguyenrom** [comment]
Thanks @Code-Egg so much, It working now 👍🏻
