### ISSUE TITLE
Out of Date OWASP Being Installed With This Setup

### ISSUE THREAD

**Issue by timnolte** [litespeedtech/ols-docker-env#54]
https://github.com/litespeedtech/ols-docker-env/blob/55b742ae33eead50dce8c5487d07913aa912e144/bin/container/owaspctl.sh#L151

The version of OWASP rules that the[ script is installing](https://github.com/SpiderLabs/owasp-modsecurity-crs) has not been updated since 2020 as it was moved to a [new repository](https://github.com/coreruleset/coreruleset). Version 3.3.4 is the latest [v3 tagged release](https://github.com/coreruleset/coreruleset/tree/v3.3.4).

**Comment by Code-Egg** [comment]
Thanks, I just pushed a [commit](https://github.com/litespeedtech/ols-docker-env/commit/3ca69edb9b9ab694aaff8e4446ca3a8e9ec0ef4d) to have the new version included, feel free to give it a try.
