### ISSUE TITLE
ssl for ports 8443 and 7080

### ISSUE THREAD

**Issue by jaseppan** [litespeedtech/ols-docker-env#55]
I followed installation instruction, but I couldn't figure out how enable ssl for ports 8443 and 7080. Could you complete the instruction?

**Comment by Code-Egg** [comment]
HI
Self-signed SSL certificates are automatically created for the Web Admin GUI at port 7080. If you have a domain and valid cert already, then you can go to LiteSpeed web admin > WebAdmin Settings > Listeners > SSL to use the valid key & cert. 
For the phpmyadmin, it's another container, please check https://docs.bitnami.com/aws/apps/wordpress/configuration/enable-basic-auth/ and https://docs.bitnami.com/virtual-machine/apps/akeneo/administration/create-ssl-certificate-apache/ for more information.
