### ISSUE TITLE
Can I custom php.ini per vhost?

### ISSUE THREAD

**Issue by nguyenrom** [litespeedtech/ols-docker-env#57]
Hi,

I tried to add php.ini to the vhost (public path), but it's not working. Is it possible to customize the php.ini file for each vhost? Each vhost uses different PHP settings or use only one php.ini for all vhosts?

Thank you,
Nguyen

**Comment by Code-Egg** [comment]
Hi @nguyenrom, 

For one php.ini for all vhosts, just edit the php.ini file directly, and it should work. You can also bind mount php.ini by [following this guide](https://docs.litespeedtech.com/cloud/docker/ols-wordpress/#how-do-i-add-a-bind-mount-for-phpini). 

OpenLiteSpeed's Docker solution uses docker.conf as a template config file by default. So setting the php.ini in each vhosts may not work. I think you need to [create dedicated vhosts](https://openlitespeed.org/kb/change-php-settings-by-vhost-and-user/) and then follow [the override global php.ini guide](https://openlitespeed.org/kb/change-php-settings-by-vhost-and-user/#Override_Global_phpini_With_Local_phpini_through_Virtual_Host_external_app).

**Comment by Code-Egg** [comment]
Hi @nguyenrom,
I just tested the above solution and it works, will close the issue.
