### ISSUE TITLE
Podman compatibility

### ISSUE THREAD

**Issue by xxxcrow** [litespeedtech/ols-docker-env#59]
Hi, on your website in the tutorial for this repo you have FAQ and there's a statement that podman is compatible

But in bin/*.sh I get:
```
bash bin/domain.sh -A test.com
Error: unknown shorthand flag: 's' in -s
See 'podman --help'
Error: unknown shorthand flag: 'T' in -T
See 'podman --help'
```

The images are compatible, but inability to run the scripts defeats the purpose of this ols-wordpress repo 😅

**Comment by xxxcrow** [comment]
It is possible to achieve the same result by modifying the command in the script to

podman-compose exec container "su -s /bin/bash lsadm..."

The only thing that podman-compose is specific to podman-compose, so no docker-compose

**Comment by xxxcrow** [comment]
Another problem that I don't have lsadm for some reason 😑

**Comment by xxxcrow** [comment]
Ok, maybe I was a little dramatic with my view and solutions I came up with

The solution I very-very simple, just replace "docker compose" to "podman-compose" (in case of podman-compose"

**Comment by Code-Egg** [comment]
Hi @xxxcrow 
I remember `docker compose` supports podman, so the issue just got resolved after you use the `podman-compose` ?

**Comment by xxxcrow** [comment]
It seems to be!

Please mention this in the docs
There are two options to use compose in podman
One is just to connect docker-compose to the podman's socket, no sure if it aliases docker compose to docker-compose somewhere, but I think it did at some point(or maybe not, maybe the errors about the flags didn't show the errors about the "podman compose". And docker-compose option didn't actually work for me
And the other one is a standalone podman-compose project, which in my opinion works way better than docker-compose
In this case you need just to replace docker compose with podman-compose

**Comment by Code-Egg** [comment]
[Doc is updated](https://docs.litespeedtech.com/cloud/docker/ols-wordpress/#is-podman-compatible-with-the-solution), issue close.
