### ISSUE TITLE
dedicated virtual host

### ISSUE THREAD

**Issue by xcpdq** [litespeedtech/ols-docker-env#6]
Hi,

I followed this documention to install OLS on docker: https://docs.litespeedtech.com/docker/openlitespeed.

 I noticed the virtual hosts are added inside a template under ViHost Templates after executing the `bash bin/domain.sh -add domain.com` command.

Would it be possible to create a dedicated virtual host directly? (the ones can be found under Virtual Hosts).

Any help is much appreciated!

**Comment by Code-Egg** [comment]
Great suggestion, it's actually on our to-do, will implement the virtual host way once new OpenLiteSpeed conf system is ready. No ETA by the way.

**Comment by nopynoop** [comment]
+1

**Comment by psavva** [comment]
+1
