### ISSUE TITLE
How to set upload_max_size to install Duplicator Pro ??

### ISSUE THREAD

**Issue by bayardorivas** [litespeedtech/ols-docker-env#61]
I am running ols-docker-env, follow the steps and everything looks fine. I wanted to install the "Duplicator Pro Pluggin" in WordPress, and everytime I tried it was refused because upload_max_size = 2Mb. Using "Big File Upload" pluggin I changed the setting to 64Mb even "Duplicator Pro" is a smaller installation file. When I try to upload media files, I don't have problem to do it, even with image files of 20Mb.

What is the directive that will allow the installation??

**Comment by Code-Egg** [comment]
Hi @bayardorivas ,
I'd recommend you bind mount php.ini first, then increase the value from there. 
More https://docs.litespeedtech.com/cloud/docker/ols-wordpress/#how-do-i-add-a-bind-mount-for-phpini
Note, please substitute the PHP version with your actual version.

**Comment by bayardorivas** [comment]
Hey @Code-Egg , thanks for your time. I read your recommendation.  I had problems with the path in the guide but gave me a good idea and to solve quick my problem I got into the litespeed container and there I edited directly the php.ini file without create a mount -volume for this file. I really thought that the php.ini file in the folder admin-conf was a volume. 

Thank you again.
