### ISSUE TITLE
Support many php version in onelitespeed

### ISSUE THREAD

**Issue by lhthang1998** [litespeedtech/ols-docker-env#62]
Hi,
I'd like to set up the app with PHP version I choose. I.e: app1 with php74 and app2 with php80
Is it possible to do configure many PHP version in ols-docker-env like that?
Thanks

**Comment by qtwrk** [comment]
https://openlitespeed.org/kb/setup-ols-with-more-than-one-php-build/

https://openlitespeed.org/kb/setup-per-directory-file-php/

basically , you can install desired PHP version , set up external app,  then in each vhost , set the script handler to designated PHP, or use rewrite rule directive

**Comment by lhthang1998** [comment]
thanks
just 1 more thing, after the above setup. how I could tell/configure/link the app/domain to the PHP version I want

**Comment by qtwrk** [comment]
I know thing or two about OLS, but not the docker , so this is based on my experience with normal Linux 

1) install php74 and php80 if needed 

2) configure 2 external app , one for 74 one for 80 , either both at server level , or one per each domain 

3) once ext app is created,  you can set up the script handler to corresponding ext app,  like domain A to php74 ext app , and domain B to php80 ext app

https://youtu.be/urnHwEQ2eAE?t=302

**Comment by lhthang1998** [comment]
thank you sm

**Comment by computocell** [comment]
Obrigado

> I know thing or two about OLS, but not the docker , so this is based on my experience with normal Linux
> 
> 1. install php74 and php80 if needed
> 2. configure 2 external app , one for 74 one for 80 , either both at server level , or one per each domain
> 3. once ext app is created,  you can set up the script handler to corresponding ext app,  like domain A to php74 ext app , and domain B to php80 ext app
> 
> https://youtu.be/urnHwEQ2eAE?t=302

Muito Obrigado.
