### ISSUE TITLE
How to install Laravel App and run composer?

### ISSUE THREAD

**Issue by wowthemes** [litespeedtech/ols-docker-env#64]
Is there any support to install the Laravel App?

Also, I am using root/sage. How to run composer or node on the server?

**Comment by Code-Egg** [comment]
@wowthemes 
I've created one for laravel app, but it is mainly for testing purposes, [feel free to give it a try](https://github.com/Code-Egg/ols-laravel-env). 
The current ols-docker-env does not support root's sage, you might want to install those packages manually from the docker container, or add it to the docker-compose file and build a custom image.

**Comment by wowthemes** [comment]
@Code-Egg , Thanks for the reply.
I've managed it within the same container. I have created a vhost from vhost template in Litespeed admin panel and modified the paths as required. 
For composer, I have installed composer in LiteSpeed image even if I restart the container it shouldn't lose any manual installation.

**Comment by Code-Egg** [comment]
Good to know you have managed to make it work. Yes, the files/data under the document root will persist.
If you also want to keep the composer software, better to build a custom image, check https://github.com/litespeedtech/ols-docker-env#customization for more information. 
Issue close.
