### ISSUE TITLE
Install PHP extensions

### ISSUE THREAD

**Issue by Haschtl** [litespeedtech/ols-docker-env#66]
I followed the README with the Dockerfile customization:
```
FROM litespeedtech/openlitespeed:latest
RUN apt-get update && apt-get install lsphp80-pspell -y
```

The packages I need, are `lsphp81-soap` and `lsphp81-xml`, which are not found, when building the Dockerfile:

```
1.539 E: Unable to locate package lsphp81-xml
1.539 E: Unable to locate package lsphp81-soap
```

Is there any other way for installing lsphp81 extensions?

**Comment by Code-Egg** [comment]
Hi @Haschtl 
I think the default lsphp81-common package should have both covered, so you can skip this step. 
Here's the package list, https://rpms.litespeedtech.com/debian/pool/main/jammy/
