### ISSUE TITLE
Change Mysql Password

### ISSUE THREAD

**Issue by gnumarquez** [litespeedtech/ols-docker-env#67]
How i can change mysql pasword after docker started?

**Comment by Code-Egg** [comment]
Hi, [this post](https://stackoverflow.com/questions/48249912/change-mysql-password-in-docker-container) should help.

**Comment by gnumarquez** [comment]
i know this method, but i thinked that exists a openlitespeed script for this operation

**Comment by Code-Egg** [comment]
We don't have a script feature for this, the shared method is commonly used in general. Another method is to change the password from the phpmyadmin.
