### ISSUE TITLE
Container restarting

### ISSUE THREAD

**Issue by notio-ca** [litespeedtech/ols-docker-env#69]
When starting litespeedtech/openlitespeed:latest , I receive the following error in the log and container is restarting in a loop:

[ERROR] Cannot find /usr/local/lsws/bin/litespeed

**Comment by Code-Egg** [comment]
Hi, please access the Docker container, and share the output with the following command: 
```
ll /usr/local/lsws/bin
```

**Comment by notio-ca** [comment]
Thanks for the quick follow up, I am unable to execute a command in the container since it's constantly restarting.
I tried to isolate the probleme as much as possible, no volume mounted, basic container startup.
Should be easy to reprodure
Thanks again!

**Comment by notio-ca** [comment]
I was able to run it with a different version, thanks for your support
