### ISSUE TITLE
SSH?

### ISSUE THREAD

**Issue by Tech-Nomad** [litespeedtech/ols-docker-env#7]
Hello! 
Thank you for this setup! 

But I can't ssh into the container. SSH isn't installed by default when running docker-compose. And when I install it manually on the running container and try then to login I get the "ssh_exchange_identification: Connection closed by remote host" message. 

How can I login into both of the containers (litespeed and mysql) via SSH? I need especially the SSH login into the mysql container to be able to access the database via Datagrip (which is much better than PhpMyAdmin).

**Comment by Code-Egg** [comment]
If general docker container access method can't satisfy the Datagrip, e.g. 
```
docker exec CONTAINER_NAME su -s /bin/bash root -c "mysql -u root -pXXXXX -e 'show databases'"
```
then you not only need to install SSH but also allow port 22 from `docker-compose.yml` file. As you can see we only allow port 8080 and 8443 on the phpmyadmin container.

**Comment by Tech-Nomad** [comment]
Hey, thank you for the quick response! 
Yes, I was aware of the need to map the ssh port and have added it to docker-compose.yml. 
The issue was caused by wrong docker command I have used :D 
Instead of `docker-compose up --build` I was running all the time `docker-compose up` after I made any changes in the configs :)
