### ISSUE TITLE
logging to stdout

### ISSUE THREAD

**Issue by psy0rz** [litespeedtech/ols-docker-env#77]
What is the recommended way to get his container to do its logging to stdout/err like a good docker citizen?

Now its writing to various logfiles, which is not the "Docker Way(tm)"

Also: Why is there an entrypoint.sh with a monitoring while loop?

Cant we just directly exec the openlitespeed binary directly from that script, so it will become PID 1? Which is also more in line with docker guidelines and perhaps makes the logging issue easier to solve?

Thanks

**Comment by Code-Egg** [comment]
Hi, 
The general command should work, e.g. `docker logs your_container_id` or `docker compose logs`. 
I'm not sure which logfiles you mean, please share the log path or any example. 
Because OLS does not have daemon mode.
