### ISSUE TITLE
Access site without port number in the URL

### ISSUE THREAD

**Issue by Tech-Nomad** [litespeedtech/ols-docker-env#8]
Hi again! :) 
I am trying to setup a site in a way that I can access it just by "https://docker.openlitespeed". But when I add this to my local Apache's configs:

```
<VirtualHost docker.openlitespeed:80>
        RequestHeader set X-Forwarded-Proto "http"
        ProxyPreserveHost On
        ProxyRequests Off
        ServerName docker.openlitespeed
        ServerAlias www.docker.openlitespeed
        ProxyPass / http://localhost:10013/
        ProxyPassReverse / http://localhost:10013/
</VirtualHost>

<VirtualHost docker.openlitespeed:443>
    RequestHeader set X-Forwarded-Proto "https"
    ProxyPreserveHost On
    ProxyRequests Off
    ServerName docker.openlitespeed
    ServerAlias www.docker.openlitespeed
    ProxyPass / http://localhost:10014/
    ProxyPassReverse / http://localhost:10014/
</VirtualHost>
```
... then the http proxy redirect works fine. But when accessing the site with https:// then I get a too many redirects error. 

Couldn't find any solutions on the web or in the forum :( 

Any Idea how to set the Openlitespeed configs to handle https requests without redirect loops?

**Comment by Tech-Nomad** [comment]
one thing more: when adding the mapped port number to the url then it works:
https://docker.litespeed:10014
or
https://localhost:10014


**Comment by Tech-Nomad** [comment]
Ok, solved it. I had to comment out some HTTPS options in the httpd_config.conf:
`
listener HTTPS {
  address                 *:443
  #secure                  1
  #keyFile                 /usr/local/lsws/admin/conf/webadmin.key
  #certFile                /usr/local/lsws/admin/conf/webadmin.crt
}`
The openlitespeed ssl certificate seems to have a conflict with my local one

**Comment by Code-Egg** [comment]
huh, ok . So you were trying to use Apache as a proxy? Then you can not get the benefit of openlitespeed cache solution and HTTP/3.

**Comment by Tech-Nomad** [comment]
Yes, I have Apache running on my local machine which I need for a bunch of other projects. So I have to proxy. Otherwise I would have to set the hostname to localhost:10014  which is ugly to work with and difficult to remember. But caching works fine as it seems - it's fast and I get "X-LiteSpeed-Cache: hit" in the Response Headers. But HTTP/2 push doesn't work indeed...

**Comment by Code-Egg** [comment]
I never tried that proxy to litespeed before, good to know that cache works well.
