### ISSUE TITLE
Sending Mail Doesn't works

### ISSUE THREAD

**Issue by SaFi2266** [litespeedtech/ols-docker-env#82]
Within **ols-docker-env** the WordPress sites, mailing function does not work at all.
I have already "Postfix" installed on my host, So how it's possible to docker environment use the SMTP server on host to sending mails?
I tried to set my IPs from [this post](https://handyman.dulare.com/sending-emails-from-docker-using-postfix-installed-on-the-host/) but it does not work either.
Would you Kindly suggest proper solutions to bypass this issue

Thank you ALL

**Comment by Code-Egg** [comment]
Hi,
Since it's a container, better not to access the host server, instead, you can prepare another container for postfix and add it to the docker-compose.yml file.

**Comment by SaFi2266** [comment]
> Hi,
> Since it's a container, better not to access the host server, instead, you can prepare another container for postfix and add it to the docker-compose.yml file. 

Great, thank you for reply
I am also thought about this since there is a cool project "mailserver on docker" , but What about mail ports opening on host I use Postfix for another app on my host and I do not want disable or remove postfix

**Comment by Code-Egg** [comment]
If you have to keep the postfix on hosts, then you can set it like [this Sending email from docker through Postfix installed on the host post](https://satishgandham.com/2016/12/sending-email-from-docker-through-postfix-installed-on-the-host/)
