### ISSUE TITLE
PHP not working on Ubuntu 24.04

### ISSUE THREAD

**Issue by udayongky** [litespeedtech/ols-docker-env#83]
Hi there,

I am trying this repo on Ubuntu Desktop 22.04. I followed the instructions on the README.md, then create and visit `info.php`. It working fine.

When I am trying this repo on Ubuntu Desktop 24.04, then create and visit `info.php`, I see a 503 Service Unavailable when loading PHP file.

The steps I did was:
```
docker compose up -d
echo '<?php phpinfo();' > sites/localhost/html/info.php
```
Then visit localhost/info.php

`stderr.log` output
```
2024-08-23 03:18:30.077 [STDERR] lscgid: execve():/usr/local/lsws/fcgi-bin/lsphp: Resource temporarily unavailable
```

Docker version: 27.1.2
Docker compose version: 2.27.0
Ubuntu Desktop version 24.04
Ubuntu Setup with Omakub version 1.1.3

Kind regards

**Comment by udayongky** [comment]
I am trying this repo on another laptop with:
Ubuntu Desktop version 24.04
Ubuntu Setup with Omakub version 1.1.3
Docker version: 27.1.2
Docker compose version: 2.27.0
And it working fine. No 503.
That's weird. :confused:

**Comment by udayongky** [comment]
I solved this with
```
docker compose down
docker system prune -af
docker volume prune -af
docker compose up -d
```
This repo now work normally on my machine.
Luckily it not occur in production docker

**Comment by Code-Egg** [comment]
@udayongky 
So reinstall the docker on your hosts which fixed the issue, is that correct?

**Comment by udayongky** [comment]
> @udayongky So reinstall the docker on your hosts which fixed the issue, is that correct?

Yes

**Comment by Code-Egg** [comment]
Thanks for the clarification, I will close the issue.
