### ISSUE TITLE
DB access failed, please check!

### ISSUE THREAD

**Issue by nikohann** [litespeedtech/ols-docker-env#88]
root@ubuntu-2gb-ash-1:~/ols-docker-env# bash bin/database.sh --domain staging.example.com
[X] DB access failed, please check!

**Comment by Code-Egg** [comment]
[The latest commit](https://github.com/litespeedtech/ols-docker-env/commit/6714d56979c2704b13983717b5344567810c144c) should have it fixed, feel free to give it a try.
