### ISSUE TITLE
Stack deploy issue

### ISSUE THREAD

**Issue by k4mrul** [litespeedtech/ols-docker-env#9]
Hello, the compose file along with other scripts do not work in docker stack. Whenever I issue this command `docker stack deploy -c docker-compose.yml mystack`, it throws an error. It would be great if you release a stack ready version. Thanks

**Comment by Code-Egg** [comment]
Thanks for the reporting.  It seems the environment variable did not pass to the `OLS_VERSION` and `PHP_VERSION` from .env file. And this suppose to be fixed after docker version 17.04 from my understanding https://github.com/moby/moby/pull/30781. 

Can you help to confirm if update from 
`image: litespeedtech/openlitespeed:${OLS_VERSION}-${PHP_VERSION}`
to 
`image: litespeedtech/openlitespeed:1.6.9-lsphp74`
works in your case? 

If you don't need Multi-host supported, `docker-compose up -d` should just works.
