### ISSUE TITLE
unknown shorthand flag: 's' in -s

### ISSUE THREAD

**Issue by edemPy** [litespeedtech/ols-docker-env#90]
Hello, what could be the reason, please tell me what to do

root@server:~/ols-docker-env# bash bin/webadmin.sh sample
Update web admin password.
unknown shorthand flag: 's' in -s
See 'docker --help'.

**Comment by Code-Egg** [comment]
Hi,
Not sure where that "s" coming from, could you run `bash -x bin/webadmin.sh sample` and share the whole output here?

**Comment by hellfi** [comment]
that "s" is coming from an outdated docker installation where "docker-compose" is used instead of "docker compose"
updating docker or substituting all "docker compose" with "docker-compose" in bin/ solves this
