### ISSUE TITLE
Today my website is not showing up it just shows 404 page

### ISSUE THREAD

**Issue by elcasano** [litespeedtech/ols-docker-env#91]
I created a blog site with Wordpress a few days ago and have some posts on it. Everything was fine until this morning, when I access my domain name, it does not show up.
When I access it with my internal IP address, the site returns a 404 page.
When I check my site in the ols-docker-env/sites directory. It still exists.
Can you guys help me solve this problem, I would appreciate it very much.

p/s: I can still access the phpMyadmin page and the OLS webadmin page normally.

**Comment by elcasano** [comment]
I'm sorry, the problem is that my domain name is not pointing to the correct server IP :D

**Comment by Code-Egg** [comment]
Don't worry, I'm glad to hear you've identified the issue!
